fix: fixes in homebrew errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -73,15 +73,15 @@ jobs:
           ANSIBLE_FORCE_COLOR: '1'
 
       - name: Idempotence check.
-          run: |
-            idempotence=$(mktemp)
-            ansible-playbook tests/test.yml | tee -a ${idempotence}
-            tail ${idempotence} \
-              | grep -q 'changed=0.*failed=0' \
-              && (echo 'Idempotence test: pass' && exit 0) \
-              || (echo 'Idempotence test: fail' && exit 1)
-          env:
-            ANSIBLE_FORCE_COLOR: '1'
+        run: |
+          idempotence=$(mktemp)
+          ansible-playbook tests/test.yml | tee -a ${idempotence}
+          tail ${idempotence} \
+            | grep -q 'changed=0.*failed=0' \
+            && (echo 'Idempotence test: pass' && exit 0) \
+            || (echo 'Idempotence test: fail' && exit 1)
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
 
   publish:
     if: github.event.inputs.shouldPublishImage == 'yes' || github.ref == 'refs/heads/master'
