ci: changes in ci workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,10 +35,10 @@ jobs:
           pip3 install yamllint
           pip3 install ansible-lint
 
-      - name: Run yamllint
+      - name: Run yamllint.
         run: yamllint .
 
-      - name: Run ansible lint
+      - name: Run ansible lint.
         working-directory: tests
         run: ansible-lint test.yml -c ../.ansible-lint
 
@@ -47,7 +47,7 @@ jobs:
         run: ansible-playbook test.yml --syntax-check
 
   integration:
-    name: Integration
+    name: Integration.
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -61,22 +61,27 @@ jobs:
         with:
           python-version: 3.9
 
-      - name: Install dependencies
+      - name: Install dependencies.
         run: |
           set -eux
           pip install ansible
           ansible-galaxy install -r requirements.yml
 
       - name: Test the playbook.
-        run: |
-          idempotence=$(mktemp)
-          ansible-playbook tests/test.yml | tee -a ${idempotence}
-          tail ${idempotence} \
-            | grep -q 'changed=0.*failed=0' \
-            && (echo 'Idempotence test: pass' && exit 0) \
-            || (echo 'Idempotence test: fail' && exit 1)
+        run: ansible-playbook tests/test.yml
         env:
           ANSIBLE_FORCE_COLOR: '1'
+
+      - name: Idempotence check.
+          run: |
+            idempotence=$(mktemp)
+            ansible-playbook tests/test.yml | tee -a ${idempotence}
+            tail ${idempotence} \
+              | grep -q 'changed=0.*failed=0' \
+              && (echo 'Idempotence test: pass' && exit 0) \
+              || (echo 'Idempotence test: fail' && exit 1)
+          env:
+            ANSIBLE_FORCE_COLOR: '1'
 
   publish:
     if: github.event.inputs.shouldPublishImage == 'yes' || github.ref == 'refs/heads/master'
